window.soundbuttons = [
	"💨 Farts and Burps 💨",
    ["Dry Fart","dryfart.mp3","FartButtons","saddlebrown"],
    ["Short Fart","shortfart.mp3","FartButtons","saddlebrown"],
    ["Wet Fart 1","wetfart.mp3","FartButtons","saddlebrown"],
    ["Wet Fart 2","wetfart2.mp3","FartButtons","saddlebrown"],
    ["Wet Fart 3","wetfart3.mp3","FartButtons","saddlebrown"],
    ["Squeaky Fart","squeakyfart.mp3","FartButtons","saddlebrown"],
    ["Long Fart","longfart.mp3","FartButtons","saddlebrown"],
    ["Reverb Fart","reverbfart.mp3","FartButtons","saddlebrown"],
    ["Crapped Pants","crappedpants.mp3","FartButtons","saddlebrown"],
    ["Brain Fart","brainfart.mp3","FartButtons","saddlebrown"],
    ["JH Fart Beat","jhfartbeat.mp3","FartButtons","darkorange"],

	["Long Burp","longburp.wav","FartButtons","green"],
	["Big Burp","bigburp.wav","FartButtons","green"],
	["Airy Burp","airyburp.wav","FartButtons","green"],
	["Deep Burp","deepburp.wav","FartButtons","green"],
	["Deep Long Belch","deeplongbelch.wav","FartButtons","green"],
	["Short Burp","shortburp.wav","FartButtons","green"],
	
	"🧽 Spongebob Squarepants 🧽",
	["Boowomp","boowomp.mp3","Spongebob","yellow"],
    ["Dolphin Censor 1","dolphincensor.mp3","Spongebob","yellow"],
    ["This guy stinks!","thisguystinks.mp3","Spongebob","yellow"],
    ["My leg!","myleg.mp3","Spongebob","yellow"],
	["Squidward Walking","squidwardwalk.mp3","Spongebob","yellow"],
    ["Vibraphone Cue","vibraphonecue.mp3","Spongebob","yellow"],
    ["Steel Sting","spongebobsteelsting.mp3","Spongebob","yellow"],
    ["Dramatic Impact 1","dramaticimpact1.mp3","Spongebob","yellow"],
    ["Dramatic Impact 2","dramaticimpact2.mp3","Spongebob","yellow"],
    ["Dramatic Impact 3","dramaticimpact3.mp3","Spongebob","yellow"],
    ["Dramatic Impact 4","dramaticimpact4.mp3","Spongebob","yellow"],
    ["Dramatic Impact 5","dramaticimpact5.mp3","Spongebob","yellow"],
    ["Dramatic Impact 6","dramaticimpact6.mp3","Spongebob","yellow"],
    ["Patrick Trombone","patricktrombone.mp3","Spongebob","yellow"],
    ["Tomfoolery","tomfoolery.mp3","Spongebob","lightyellow"],
    ["Jellyfish Jam","stadiumrave.mp3","Spongebob","lightyellow"],
    ["The Lineman","thelineman.mp3","Spongebob","lightyellow"],
    ["Electric Zoo","electriczoo.mp3","Spongebob","lightyellow"],
	["Grass Skirt Chase","grassskirtchase.mp3","Spongebob","lightyellow"],
    ["Living in the Sunlight","livinginthesunlight.mp3","Spongebob","lightyellow"],

	"❓ Miscellaneous Sounds ❓",
	["Airhorn","airhorn.mp3","Misc","blue"],
	["Laugh Track","laughtrack.mp3","Misc","blue"],
	["Windows XP Error","windowsxperror.mp3","Misc","blue"],
	["Windows XP Shutdown","windowsxpshutdown.mp3","Misc","blue"],
	["Pop","pop.mp3","Misc","blue"],
	["Realistic Knocking","realisticknocking.mp3","Misc","blue"],
	["Sad Trombone","sadtrombone.mp3","Misc","blue"],
	["What Da Dog Doin?","whatdadogdoin.mp3","Misc","blue"],
	["Lego Break","legobreak.mp3","Misc","blue"],
	["Mario Jump","mariojump.mp3","Misc","blue"],
	["Nope","nope.mp3","Misc","blue"],
	["Roblox Oof","oof.mp3","Misc","blue"],
	["Airhorn","airhorn.mp3","Misc","blue"],
	["Aughhhhh","aughhhhh.mp3","Misc","blue"],
	["Awooga","awooga.mp3","Misc","blue"],
	["Sr Pelo Scream","srpeloscream.mp3","Misc","blue"],
	["Bruh","bruh.mp3","Misc","blue"],
	["Bad to the Bone","badtothebone.mp3","Misc","blue"],
	["FBI Open Up","fbiopenup.mp3","Misc","blue"],
	["Taco Bell","tacobellnormal.mp3","Misc","blue"],
	["Taco Bell Loud","tacobellloud.mp3","Misc","blue"],
	["Goofy Ahh","goofyahh.mp3","Misc","blue"],
	["Goofy Ahh Sleeping","goofysleeping.mp3","Misc","blue"],
	["Bonk","bonk.mp3","Misc","blue"],
	["Cartoon Run","cartoonrun.mp3","Misc","blue"],
	["Shrek Swamp","shrekswamp.mp3","Misc","blue"],
	["Airhorn","airhorn.mp3","Misc","blue"],
	["Shut Up","shutup.mp3","Misc","blue"],
	["Danger Alarm","dangeralarm.mp3","Misc","blue"],
	["Dixieland Car Horn","dixieland car horn.mp3","Misc","blue"],
	["Dramatic Chipmunk","dramaticchipmunk.mp3","Misc","blue"],
	["Dramatic Scream","dramaticscream.mp3","Misc","blue"],
    ["Water phone","waterphone.mp3","Misc","blue"],
    ["Vine BOOM!","vineboom.mp3","Misc","blue"],
    ["Ooo waaa ooo","ooowaahhooo.mp3","Misc","blue"],
	["Amogus","amogus.mp3","Misc","blue"],
	["Well Be Right Back","wellberightback.mp3","Misc","blue"],
    ["Menis Pusic","penismusic.mp3","Misc","lightblue"],
	["Coffin Dance","coffindance.mp3","Misc","lightblue"],
	["Default Dance","defaultdance.mp3","Misc","lightblue"],
	["Jeopardy","jeopardy.mp3","Misc","lightblue"],
	["Wide Putin","wideputin.mp3","Misc","lightblue"],
	["NFL Theme","nfltheme.mp3","Misc","lightblue"],
]